language: objective-c
rvm:
  - 2.2
osx_image: xcode7.3
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
notifications:
  email:
    recipients:
      - alex@alexrothenberg.com
      - jmay@pobox.com
